### ISSUE TITLE
Generate feed query

### ISSUE THREAD

**Issue by jbartulos** [adampmoss/MageFoxGoogleShopping#2]
Hi, I installed the magefox google shopping extension from github. Can you tell me how I generated the feed? Thank you very much and greetings

**Comment by luizpaulofranz** [comment]
Hi, to generate the XML Feed, just open following URL: **http://YOUR-STORE-BASE-URL/magefoxgoogleshopping**.

**Comment by I-Vaganienko** [comment]
Hello dear @adampmoss :) Can you help me please? I have installed this extension, but let me know, how can I generate XML? I get only 200 items. Not more, but on our shop +5000 items. Please tell me what I do wrong? Thank you!

**Comment by adampmoss** [comment]
@I-Vaganienko I have just merged a PR to fix this, please try again.

**Comment by I-Vaganienko** [comment]
@adampmoss thank you! Will check

**Comment by larcohex** [comment]
![image](https://user-images.githubusercontent.com/2596166/39056678-31711ffe-44d9-11e8-9ae4-7718d3b5da50.png)

**Comment by I-Vaganienko** [comment]
![image](https://user-images.githubusercontent.com/22290509/39056808-7ce47ac6-44d9-11e8-99f8-35a048a9fa01.png)

**Comment by I-Vaganienko** [comment]
Hi dear @adampmoss 

Forwarding urgent email from Google merchant center re some items at risk for disapproval. Most of the samples sent by Google are out of stock items. 

Please advise how we can trigger automatic item updates (in-stock, out of stock) to prevent being flagged for incorrect availability.

**Comment by foehlmann** [comment]
>![image](https://user-images.githubusercontent.com/22290509/39056808-7ce47ac6-44d9-11e8-99f8-35a048a9fa01.png) ...

@I-Vaganienko 

Its open... 5 month old... needed some help?
You can take quick look at the source of that page. I would think one of the needed attributes is missing...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ueltonVeslei** [comment]
Same issue here, this repo is dead?

**Comment by ueltonVeslei** [comment]
`<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getSource() on boolean in /home/mage2/public_html/vendor/magento/module-catalog/Model/Product.php:1764
Stack trace:
#0 /home/mage2/public_html/generated/code/Magento/Catalog/Model/Product/Interceptor.php(1090): Magento\Catalog\Model\Product-&gt;getAttributeText('condition')
#1 /home/mage2/public_html/app/code/Magefox/GoogleShopping/Model/Xmlfeed.php(95): Magento\Catalog\Model\Product\Interceptor-&gt;getAttributeText('condition')
#2 /home/mage2/public_html/app/code/Magefox/GoogleShopping/Model/Xmlfeed.php(75): Magefox\GoogleShopping\Model\Xmlfeed-&gt;buildProductXml(Object(Magento\Catalog\Model\Product\Interceptor))
#3 /home/mage2/public_html/app/code/Magefox/GoogleShopping/Model/Xmlfeed.php(42): Magefox\GoogleShopping\Model\Xmlfeed-&gt;getProductsXml()
#4 /home/mage2/public_html/app/code/Magefox/GoogleShopping/Controller/Index/Index.php(45): Magefox\GoogleShopping\Model\Xmlfeed-&gt;getFeed()
#5 /home/mage2/public_html/generated/code/Magefox/GoogleShopping/Controller/Index/Ind in <b>/home/mage2/public_html/vendor/magento/module-catalog/Model/Product.php</b> on line <b>1764</b><br />
`

**Comment by adampmoss** [comment]
@ueltonVeslei sorry I'm not maintaining this repo any more.

**Comment by Josiahsequoyah** [comment]
I tried this module on Magento 2 v2.3.1 and it indeed, no longer works. I received the same error as foehlmann.

**Comment by Anantkprajapati** [comment]
Hello @adampmoss - getting same error like @foehlmann , @Josiahsequoyah 
Can you please fix it and update us???

Thank you

**Comment by ATDWebmaster** [comment]
@Anantkprajapati @Josiahsequoyah @ueltonVeslei hi guys, i've find the problem in the file 
"magentoWebsite/app/code/Magefox/GoogleShopping/Controller/Index/Index.php" at line 5/6
the problem is the class "Class 'Magento\Framework\App\Action\Action'" is not found.
if anyone of you understand how to fix it, please reply me.
